# Generated by Django 2.1 on 2018-08-19 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('trip_start', models.DateTimeField()),
                ('trip_end', models.DateTimeField()),
                ('update_d', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='trips', to='beltapp.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beltapp.User')),
            ],
        ),
    ]
